#!/usr/bin/env bash
# This script installs nginx on ubuntu server

sudo apt-get update -y && sudo apt-get upgrade -y
sudo apt-get install -y nginx
sudo ufw allow 'Nginx HTTP'

echo "Hello World!" | sudo tee /var/www/html/index.html

sudo service nginx restart
