#!/usr/bin/env bash
# Web Server-02 login commands

# Setting up the SSH-agent
eval $("ssh-agent")

# Path to IdentityFile
ssh-add ~/.ssh/school.pub

# Username and IP Address 
ssh ubuntu@100.27.0.194
