#!/usr/bin/env bash
# Will display "To infinity and beyond" indefinitely with
#+ a sleep  in between each iteration.
# Will also  display "I am invincible!!!" in between each iteration.

while true
do
  echo "To infinity and beyond"
  sleep 2
  trap 'echo "I am invincible!!!"' SIGTERM 
done
