#!/usr/bin/env bash
# Script that displays the contents of the file `/etc/passwd`.
#   Will display the username, user id, and user home directory path.

myfile="/etc/passwd"
while IFS= read -r line
do
    echo "$line" | cut -d":" -f1,3,6
done < "$myfile"
