#!/usr/bin/env bash
# Script that displays the content of the current directory in list format
# Will only display the part of the name after the first dash

mylist=$(ls)

for i in $mylist; do
  echo "$i" | cut -d '-' -f2
done
